{
  "swagger": "2.0",
  "info": {
    "version": "Latest",
    "title": "ORCID Member"
  },
  "host": "api.orcid.org",
  "tags": [
    {
      "name": "Member API v2.0"
    },
    {
      "name": "Member API v2.1"
    },
    {
      "name": "Development Member API v3.0"
    },
    {
      "name": "Development Member API v3.0"
    },
    {
      "name": "Development Member API v3.0"
    },
    {
      "name": "resources"
    }
  ],
  "paths": {
    "/v3.0/apiStatus": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "operationId": "viewStatusJson"
      }
    },
    "/v3.0/{orcid}/activities": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all activities",
        "description": "",
        "operationId": "viewActivities",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/work/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch a Work",
        "description": "",
        "operationId": "viewWork",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Update a Work",
        "description": "",
        "operationId": "updateWork",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete a Work",
        "description": "",
        "operationId": "deleteWork",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/works": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all works",
        "description": "",
        "operationId": "viewWorks",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Create a list of Works",
        "description": "",
        "operationId": "createWorks",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/works/{putCodes}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch specified works",
        "description": "",
        "operationId": "viewSpecifiedWorks",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/work/summary/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch a Work Summary",
        "description": "",
        "operationId": "viewWorkSummary",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/work": {
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Create a Work",
        "description": "",
        "operationId": "createWork",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/funding/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch a Funding",
        "description": "",
        "operationId": "viewFunding",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Update a Funding",
        "description": "",
        "operationId": "updateFunding",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete a Funding",
        "description": "",
        "operationId": "deleteFunding",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/fundings": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all fundings",
        "description": "",
        "operationId": "viewFundings",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/funding/summary/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch a Funding Summary",
        "description": "",
        "operationId": "viewFundingSummary",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/funding": {
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Create a Funding",
        "description": "",
        "operationId": "createFunding",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/education/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an Education",
        "description": "",
        "operationId": "viewEducation",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Update an Education",
        "description": "",
        "operationId": "updateEducation",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete an Education",
        "description": "",
        "operationId": "deleteEducation",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/educations": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all educations",
        "description": "",
        "operationId": "viewEducations",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/education/summary/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an Education summary",
        "description": "",
        "operationId": "viewEducationSummary",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/education": {
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Create an Education",
        "description": "",
        "operationId": "createEducation",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/employment/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an Employment",
        "description": "",
        "operationId": "viewEmployment",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Update an Employment",
        "description": "",
        "operationId": "updateEmployment",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete an Employment",
        "description": "",
        "operationId": "deleteEmployment",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/employments": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all employments",
        "description": "",
        "operationId": "viewEmployments",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/employment/summary/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an Employment Summary",
        "description": "",
        "operationId": "viewEmploymentSummary",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/employment": {
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Create an Employment",
        "description": "",
        "operationId": "createEmployment",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/peer-review/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch a Peer Review",
        "description": "",
        "operationId": "viewPeerReview",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Update a Peer Review",
        "description": "",
        "operationId": "updatePeerReview",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete a Peer Review",
        "description": "",
        "operationId": "deletePeerReview",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/peer-reviews": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all peer reviews",
        "description": "",
        "operationId": "viewPeerReviews",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/peer-review/summary/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch a Peer Review Summary",
        "description": "",
        "operationId": "viewPeerReviewSummary",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/peer-review": {
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Create a Peer Review",
        "description": "",
        "operationId": "createPeerReview",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/group-id-record/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch a Group",
        "description": "",
        "operationId": "viewGroupIdRecord",
        "security": [
          {
            "orcid_two_legs": [
              "/group-id-record/read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Update a Group",
        "description": "",
        "operationId": "updateGroupIdRecord",
        "security": [
          {
            "orcid_two_legs": [
              "/group-id-record/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete a Group",
        "description": "",
        "operationId": "deleteGroupIdRecord",
        "security": [
          {
            "orcid_two_legs": [
              "/group-id-record/update"
            ]
          }
        ]
      }
    },
    "/v3.0/group-id-record": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch Groups",
        "description": "",
        "operationId": "viewGroupIdRecords",
        "security": [
          {
            "orcid_two_legs": [
              "/group-id-record/read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Create a Group",
        "description": "",
        "operationId": "createGroupIdRecord",
        "security": [
          {
            "orcid_two_legs": [
              "/group-id-record/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/notification-permission/{id}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch a notification by id",
        "description": "",
        "operationId": "viewPermissionNotification",
        "security": [
          {
            "orcid_two_legs": [
              "/premium-notification"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Archive a notification",
        "description": "",
        "operationId": "flagAsArchivedPermissionNotification",
        "security": [
          {
            "orcid_two_legs": [
              "/premium-notification"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/notification-permission": {
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Add a notification",
        "description": "",
        "operationId": "addPermissionNotification",
        "security": [
          {
            "orcid_two_legs": [
              "/premium-notification"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/researcher-urls": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all researcher urls for an ORCID ID",
        "description": "",
        "operationId": "viewResearcherUrls",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Add a new researcher url for an ORCID ID",
        "description": "",
        "operationId": "createResearcherUrl",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/researcher-urls/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch one researcher url for an ORCID ID",
        "description": "",
        "operationId": "viewResearcherUrl",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Edits researcher url for an ORCID ID",
        "description": "",
        "operationId": "editResearcherUrl",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete one researcher url from an ORCID ID",
        "description": "",
        "operationId": "deleteResearcherUrl",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/email": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all emails for an ORCID ID",
        "description": "",
        "operationId": "viewEmails",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/other-names/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch Other name",
        "description": "",
        "operationId": "viewOtherName",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Edit other name",
        "description": "",
        "operationId": "editOtherName",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete other name",
        "description": "",
        "operationId": "deleteOtherName",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/other-names": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch Other names",
        "description": "",
        "operationId": "viewOtherNames",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Add other name",
        "description": "",
        "operationId": "createOtherName",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/personal-details": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch personal details for an ORCID ID",
        "description": "",
        "operationId": "viewPersonalDetails",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/external-identifiers/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch external identifier",
        "description": "",
        "operationId": "viewExternalIdentifier",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Edit external identifier",
        "description": "",
        "operationId": "editExternalIdentifier",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete external identifier",
        "description": "",
        "operationId": "deleteExternalIdentifier",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/external-identifiers": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch external identifiers",
        "description": "",
        "operationId": "viewExternalIdentifiers",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Add external identifier",
        "description": "",
        "operationId": "createExternalIdentifier",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/biography": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Get biography details",
        "description": "",
        "operationId": "viewBiography",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/keywords/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch keyword",
        "description": "",
        "operationId": "viewKeyword",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Edit keyword",
        "description": "",
        "operationId": "editKeyword",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete keyword",
        "description": "",
        "operationId": "deleteKeyword",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/keywords": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch keywords",
        "description": "",
        "operationId": "viewKeywords",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Add keyword",
        "description": "",
        "operationId": "createKeyword",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/address/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an address",
        "description": "",
        "operationId": "viewAddress",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Edit an address",
        "description": "",
        "operationId": "editAddress",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete an address",
        "description": "",
        "operationId": "deleteAddress",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/address": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all addresses of a profile",
        "description": "",
        "operationId": "viewAddresses",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Add an address",
        "description": "",
        "operationId": "createAddress",
        "security": [
          {
            "orcid_auth": [
              "/person/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/person": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch person details",
        "description": "",
        "operationId": "viewPerson",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch record details",
        "description": "",
        "operationId": "viewRecord",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/search": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Search records",
        "description": "",
        "operationId": "searchByQuery",
        "security": [
          {
            "orcid_two_legs": [
              "/read-public"
            ]
          }
        ]
      }
    },
    "/v3.0/client/{client_id}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch client details",
        "description": "",
        "operationId": "viewClient",
        "security": [
          {
            "orcid_two_legs": [
              "/read-public"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/distinction/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an Distinction",
        "description": "",
        "operationId": "viewDistinction",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Update an Distinction",
        "description": "",
        "operationId": "updateDistinction",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete an Distinction",
        "description": "",
        "operationId": "deleteDistinction",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/distinctions": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all distinctions",
        "description": "",
        "operationId": "viewDistinctions",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/distinction/summary/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an Distinction summary",
        "description": "",
        "operationId": "viewDistinctionSummary",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/distinction": {
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Create an Distinction",
        "description": "",
        "operationId": "createDistinction",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/invited-position/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an InvitedPosition",
        "description": "",
        "operationId": "viewInvitedPosition",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Update an InvitedPosition",
        "description": "",
        "operationId": "updateInvitedPosition",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete an InvitedPosition",
        "description": "",
        "operationId": "deleteInvitedPosition",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/invited-positions": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all invitedPositions",
        "description": "",
        "operationId": "viewInvitedPositions",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/invited-position/summary/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an InvitedPosition summary",
        "description": "",
        "operationId": "viewInvitedPositionSummary",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/invited-position": {
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Create an InvitedPosition",
        "description": "",
        "operationId": "createInvitedPosition",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/membership/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an Membership",
        "description": "",
        "operationId": "viewMembership",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Update an Membership",
        "description": "",
        "operationId": "updateMembership",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete an Membership",
        "description": "",
        "operationId": "deleteMembership",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/memberships": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all memberships",
        "description": "",
        "operationId": "viewMemberships",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/membership/summary/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an Membership summary",
        "description": "",
        "operationId": "viewMembershipSummary",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/membership": {
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Create an Membership",
        "description": "",
        "operationId": "createMembership",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/qualification/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an Qualification",
        "description": "",
        "operationId": "viewQualification",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Update an Qualification",
        "description": "",
        "operationId": "updateQualification",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete an Qualification",
        "description": "",
        "operationId": "deleteQualification",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/qualifications": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all qualifications",
        "description": "",
        "operationId": "viewQualifications",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/qualification/summary/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an Qualification summary",
        "description": "",
        "operationId": "viewQualificationSummary",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/qualification": {
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Create an Qualification",
        "description": "",
        "operationId": "createQualification",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/service/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an Service",
        "description": "",
        "operationId": "viewService",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Update an Service",
        "description": "",
        "operationId": "updateService",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete an Service",
        "description": "",
        "operationId": "deleteService",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/services": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all services",
        "description": "",
        "operationId": "viewServices",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/service/summary/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch an Service summary",
        "description": "",
        "operationId": "viewServiceSummary",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/service": {
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Create an Service",
        "description": "",
        "operationId": "createService",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/research-resource/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch a Research Resource",
        "description": "",
        "operationId": "viewResearchResource",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Update a Research Resource",
        "description": "",
        "operationId": "updateResearchResource",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Delete an Research Resource",
        "description": "",
        "operationId": "deleteResearchResource",
        "security": [
          {
            "orcid_auth": [
              "/activities/update"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/research-resources": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch all Research Resources",
        "description": "",
        "operationId": "viewResearchResources",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/research-resource/summary/{putCode}": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Fetch a Research Resource summary",
        "description": "",
        "operationId": "viewResearchResourceSummary",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/{orcid}/research-resource": {
      "post": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Create a Research Resource",
        "description": "",
        "operationId": "createResearchResource",
        "security": [
          {
            "orcid_auth": [
              "/read-limited"
            ]
          }
        ]
      }
    },
    "/v3.0/csv-search": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Search records",
        "description": "",
        "operationId": "searchByQuery"
      }
    },
    "/v3.0/expanded-search": {
      "get": {
        "tags": [
          "Development Member API v3.0"
        ],
        "summary": "Search records",
        "description": "",
        "operationId": "searchByQuery"
      }
    }
  },
  "securityDefinitions": {
    "orcid_auth": {
      "type": "oauth2",
      "authorizationUrl": "https://orcid.org/oauth/authorize",
      "tokenUrl": "https://pub.orcid.org/oauth/token",
      "flow": "accessCode",
      "scopes": {
        "/read-limited": "Read Limited record",
        "/person/update": "Update person",
        "/activities/update": "Update activities"
      }
    },
    "orcid_two_legs": {
      "type": "oauth2",
      "tokenUrl": "https://pub.orcid.org/oauth/token",
      "flow": "application",
      "scopes": {
        "/premium-notification": "Notifications",
        "/read-public": "Read Public record",
        "/group-id-record/read": "Read groups",
        "/group-id-record/update": "Update groups"
      }
    }
  }
}